class PopulateCities < ActiveRecord::Migration
  def self.up
    City.create :name => "Port blair", :region => "Andaman & Nicobar Islands"
    City.create :name => "Other city", :region => "Andaman & Nicobar Islands"
    City.create :name => "Daman", :region => "Daman & Diu"
    City.create :name => "Other city", :region => "Daman & Diu"
    City.create :name => "Other city", :region => "Chandigarh"
    City.create :name => "Chandigarh", :region => "Chandigarh"
    City.create :name => "Silvassa", :region => "Dadra & Nagar Haveli"
    City.create :name => "Other city", :region => "Dadra & Nagar Haveli"
    City.create :name => "All cities", :region => "Lakshadweep"
    City.create :name => "Other city", :region => "Delhi"
    City.create :name => "Delhi", :region => "Delhi"
    City.create :name => "Karaikal", :region => "Pondicherry"
    City.create :name => "Pondicherry", :region => "Pondicherry"
    City.create :name => "Other city", :region => "Pondicherry"
    City.create :name => "Nellore", :region => "Andhra Pradesh"
    City.create :name => "Ongole", :region => "Andhra Pradesh"
    City.create :name => "Rajahmundry", :region => "Andhra Pradesh"
    City.create :name => "Secunderabad", :region => "Andhra Pradesh"
    City.create :name => "Tirupati", :region => "Andhra Pradesh"
    City.create :name => "Adilabad", :region => "Andhra Pradesh"
    City.create :name => "Vijayawada", :region => "Andhra Pradesh"
    City.create :name => "Anantapur", :region => "Andhra Pradesh"
    City.create :name => "Visakhpatnam", :region => "Andhra Pradesh"
    City.create :name => "Chittoor", :region => "Andhra Pradesh"
    City.create :name => "Warangal", :region => "Andhra Pradesh"
    City.create :name => "Vizianagaram", :region => "Andhra Pradesh"
    City.create :name => "Guntur", :region => "Andhra Pradesh"
    City.create :name => "Other city", :region => "Andhra Pradesh"
    City.create :name => "Kakinada", :region => "Andhra Pradesh"
    City.create :name => "Hyderabad", :region => "Andhra Pradesh"
    City.create :name => "Kurnool", :region => "Andhra Pradesh"
    City.create :name => "Other city", :region => "Arunachal Pradesh"
    City.create :name => "Itanagar", :region => "Arunachal Pradesh"
    City.create :name => "Guwahati", :region => "Assam"
    City.create :name => "Other city", :region => "Assam"
    City.create :name => "Muzaffarpur", :region => "Bihar"
    City.create :name => "Patna", :region => "Bihar"
    City.create :name => "Other city", :region => "Bihar"
    City.create :name => "Bilaspur", :region => "Chhattisgarh"
    City.create :name => "Bhilai", :region => "Chhattisgarh"
    City.create :name => "Raipur", :region => "Chhattisgarh"
    City.create :name => "Other city", :region => "Chhattisgarh"
    City.create :name => "Mormugao", :region => "Goa"
    City.create :name => "Panaji", :region => "Goa"
    City.create :name => "Other city", :region => "Goa"
    City.create :name => "Madgaon", :region => "Goa"
    City.create :name => "Rajkot", :region => "Gujarat"
    City.create :name => "Surat", :region => "Gujarat"
    City.create :name => "Vadodara", :region => "Gujarat"
    City.create :name => "Vapi", :region => "Gujarat"
    City.create :name => "Ahmedabad", :region => "Gujarat"
    City.create :name => "Other city", :region => "Gujarat"
    City.create :name => "Anand", :region => "Gujarat"
    City.create :name => "Bhavnagar", :region => "Gujarat"
    City.create :name => "Bharuch", :region => "Gujarat"
    City.create :name => "Bhuj", :region => "Gujarat"
    City.create :name => "Gandhidham", :region => "Gujarat"
    City.create :name => "Gandhinagar", :region => "Gujarat"
    City.create :name => "Jamnagar", :region => "Gujarat"
    City.create :name => "Karnal", :region => "Haryana"
    City.create :name => "Panchkula urban estate", :region => "Haryana"
    City.create :name => "Panipat", :region => "Haryana"
    City.create :name => "Rohtak", :region => "Haryana"
    City.create :name => "Rewari", :region => "Haryana"
    City.create :name => "Sonipat", :region => "Haryana"
    City.create :name => "Ambala", :region => "Haryana"
    City.create :name => "Yamunanagar", :region => "Haryana"
    City.create :name => "Ambala cantonment", :region => "Haryana"
    City.create :name => "Other city", :region => "Haryana"
    City.create :name => "Faridabad (new township)", :region => "Haryana"
    City.create :name => "Gurgaon", :region => "Haryana"
    City.create :name => "Hisar", :region => "Haryana"
    City.create :name => "Jind", :region => "Haryana"
    City.create :name => "Shimla", :region => "Himachal Pradesh"
    City.create :name => "Other city", :region => "Himachal Pradesh"
    City.create :name => "Srinagar", :region => "Jammu & Kashmir"
    City.create :name => "Other city", :region => "Jammu & Kashmir"
    City.create :name => "Jammu", :region => "Jammu & Kashmir"
    City.create :name => "Dhanbad", :region => "Jharkhand"
    City.create :name => "Bokaro steel city", :region => "Jharkhand"
    City.create :name => "Jamshedpur", :region => "Jharkhand"
    City.create :name => "Ranchi", :region => "Jharkhand"
    City.create :name => "Other city", :region => "Jharkhand"
    City.create :name => "Hubli-dharwar", :region => "Karnataka"
    City.create :name => "Mysore", :region => "Karnataka"
    City.create :name => "Mangalore", :region => "Karnataka"
    City.create :name => "Udupi", :region => "Karnataka"
    City.create :name => "Other city", :region => "Karnataka"
    City.create :name => "Bangalore", :region => "Karnataka"
    City.create :name => "Belgaum", :region => "Karnataka"
    City.create :name => "Bellary", :region => "Karnataka"
    City.create :name => "Gulbarga", :region => "Karnataka"
    City.create :name => "Tiruvalla", :region => "Kerala"
    City.create :name => "Kottayam", :region => "Kerala"
    City.create :name => "Other city", :region => "Kerala"
    City.create :name => "Alappuzha", :region => "Kerala"
    City.create :name => "Guruvayur", :region => "Kerala"
    City.create :name => "Kozhikode", :region => "Kerala"
    City.create :name => "Kannur", :region => "Kerala"
    City.create :name => "Malappuram", :region => "Kerala"
    City.create :name => "Kasaragod", :region => "Kerala"
    City.create :name => "Palakkad", :region => "Kerala"
    City.create :name => "Kochi", :region => "Kerala"
    City.create :name => "Thiruvananthapuram", :region => "Kerala"
    City.create :name => "Kollam", :region => "Kerala"
    City.create :name => "Thrissur", :region => "Kerala"
    City.create :name => "Bhopal", :region => "Madhya Pradesh"
    City.create :name => "Gwalior", :region => "Madhya Pradesh"
    City.create :name => "Indore", :region => "Madhya Pradesh"
    City.create :name => "Jabalpur", :region => "Madhya Pradesh"
    City.create :name => "Satna", :region => "Madhya Pradesh"
    City.create :name => "Ujjain", :region => "Madhya Pradesh"
    City.create :name => "Other city", :region => "Madhya Pradesh"
    City.create :name => "Other city", :region => "Maharashtra"
    City.create :name => "Pimpri-chinchwad", :region => "Maharashtra"
    City.create :name => "Badlapur", :region => "Maharashtra"
    City.create :name => "Pune", :region => "Maharashtra"
    City.create :name => "Dombivali", :region => "Maharashtra"
    City.create :name => "Pune cantonment", :region => "Maharashtra"
    City.create :name => "Jalgaon", :region => "Maharashtra"
    City.create :name => "Ratnagiri", :region => "Maharashtra"
    City.create :name => "Kalyan", :region => "Maharashtra"
    City.create :name => "Sangli (-miraj)", :region => "Maharashtra"
    City.create :name => "Kolhapur", :region => "Maharashtra"
    City.create :name => "Satara", :region => "Maharashtra"
    City.create :name => "Mira bhayandar", :region => "Maharashtra"
    City.create :name => "Solapur", :region => "Maharashtra"
    City.create :name => "Mumbai", :region => "Maharashtra"
    City.create :name => "Thane", :region => "Maharashtra"
    City.create :name => "Nagpur", :region => "Maharashtra"
    City.create :name => "Ulhasnagar", :region => "Maharashtra"
    City.create :name => "Nashik", :region => "Maharashtra"
    City.create :name => "Vasai", :region => "Maharashtra"
    City.create :name => "Navi mumbai", :region => "Maharashtra"
    City.create :name => "Ahmadnagar", :region => "Maharashtra"
    City.create :name => "Virar", :region => "Maharashtra"
    City.create :name => "Panvel", :region => "Maharashtra"
    City.create :name => "Amravati", :region => "Maharashtra"
    City.create :name => "Imphal", :region => "Manipur"
    City.create :name => "Other city", :region => "Manipur"
    City.create :name => "Shillong", :region => "Meghalaya"
    City.create :name => "Other city", :region => "Meghalaya"
    City.create :name => "All cities", :region => "Mizoram"
    City.create :name => "All cities", :region => "Nagaland"
    City.create :name => "Puri", :region => "Orissa"
    City.create :name => "Raurkela", :region => "Orissa"
    City.create :name => "Sambalpur", :region => "Orissa"
    City.create :name => "Other city", :region => "Orissa"
    City.create :name => "Bhubaneswar", :region => "Orissa"
    City.create :name => "Brahmapur", :region => "Orissa"
    City.create :name => "Cuttack", :region => "Orissa"
    City.create :name => "Jharsuguda", :region => "Orissa"
    City.create :name => "Patiala", :region => "Punjab"
    City.create :name => "S.a.s. nagar", :region => "Punjab"
    City.create :name => "Other city", :region => "Punjab"
    City.create :name => "Amritsar", :region => "Punjab"
    City.create :name => "Bathinda", :region => "Punjab"
    City.create :name => "Hoshiarpur", :region => "Punjab"
    City.create :name => "Jalandhar", :region => "Punjab"
    City.create :name => "Ludhiana", :region => "Punjab"
    City.create :name => "Moga", :region => "Punjab"
    City.create :name => "Pathankot", :region => "Punjab"
    City.create :name => "Other city", :region => "Rajasthan"
    City.create :name => "Ajmer", :region => "Rajasthan"
    City.create :name => "Alwar", :region => "Rajasthan"
    City.create :name => "Bhilwara", :region => "Rajasthan"
    City.create :name => "Bikaner", :region => "Rajasthan"
    City.create :name => "Jaipur", :region => "Rajasthan"
    City.create :name => "Jodhpur", :region => "Rajasthan"
    City.create :name => "Kota", :region => "Rajasthan"
    City.create :name => "Udaipur", :region => "Rajasthan"
    City.create :name => "Gangtok", :region => "Sikkim"
    City.create :name => "Other city", :region => "Sikkim"
    City.create :name => "Salem", :region => "Tamil Nadu"
    City.create :name => "Dindigul", :region => "Tamil Nadu"
    City.create :name => "Tambaram", :region => "Tamil Nadu"
    City.create :name => "Erode", :region => "Tamil Nadu"
    City.create :name => "Thanjavur", :region => "Tamil Nadu"
    City.create :name => "Hosur", :region => "Tamil Nadu"
    City.create :name => "Thoothukkudi", :region => "Tamil Nadu"
    City.create :name => "Kanchipuram", :region => "Tamil Nadu"
    City.create :name => "Ambattur", :region => "Tamil Nadu"
    City.create :name => "Tiruchirappalli", :region => "Tamil Nadu"
    City.create :name => "Karur", :region => "Tamil Nadu"
    City.create :name => "Arakonam", :region => "Tamil Nadu"
    City.create :name => "Tirunelveli", :region => "Tamil Nadu"
    City.create :name => "Kumbakonam", :region => "Tamil Nadu"
    City.create :name => "Avadi", :region => "Tamil Nadu"
    City.create :name => "Tiruppur", :region => "Tamil Nadu"
    City.create :name => "Madurai", :region => "Tamil Nadu"
    City.create :name => "Chengalpattu", :region => "Tamil Nadu"
    City.create :name => "Tiruvannamalai", :region => "Tamil Nadu"
    City.create :name => "Nagercoil", :region => "Tamil Nadu"
    City.create :name => "Chennai", :region => "Tamil Nadu"
    City.create :name => "Vellore", :region => "Tamil Nadu"
    City.create :name => "Namakkal", :region => "Tamil Nadu"
    City.create :name => "Coimbatore", :region => "Tamil Nadu"
    City.create :name => "Other city", :region => "Tamil Nadu"
    City.create :name => "Pollachi", :region => "Tamil Nadu"
    City.create :name => "Coonoor", :region => "Tamil Nadu"
    City.create :name => "Pudukkottai", :region => "Tamil Nadu"
    City.create :name => "Cuddalore", :region => "Tamil Nadu"
    City.create :name => "Other city", :region => "Tripura"
    City.create :name => "Agartala", :region => "Tripura"
    City.create :name => "Meerut", :region => "Uttar Pradesh"
    City.create :name => "Moradabad", :region => "Uttar Pradesh"
    City.create :name => "Agra", :region => "Uttar Pradesh"
    City.create :name => "Noida", :region => "Uttar Pradesh"
    City.create :name => "Aligarh", :region => "Uttar Pradesh"
    City.create :name => "Saharanpur", :region => "Uttar Pradesh"
    City.create :name => "Allahabad", :region => "Uttar Pradesh"
    City.create :name => "Varanasi", :region => "Uttar Pradesh"
    City.create :name => "Bareilly", :region => "Uttar Pradesh"
    City.create :name => "Other city", :region => "Uttar Pradesh"
    City.create :name => "Ghaziabad", :region => "Uttar Pradesh"
    City.create :name => "Gorakhpur", :region => "Uttar Pradesh"
    City.create :name => "Jhansi", :region => "Uttar Pradesh"
    City.create :name => "Kanpur", :region => "Uttar Pradesh"
    City.create :name => "Lucknow", :region => "Uttar Pradesh"
    City.create :name => "Mathura", :region => "Uttar Pradesh"
    City.create :name => "Roorkee", :region => "Uttaranchal"
    City.create :name => "Rudrapur", :region => "Uttaranchal"
    City.create :name => "Other city", :region => "Uttaranchal"
    City.create :name => "Dehra dun", :region => "Uttaranchal"
    City.create :name => "Haldwani", :region => "Uttaranchal"
    City.create :name => "Hardwar", :region => "Uttaranchal"
    City.create :name => "Kashipur", :region => "Uttaranchal"
    City.create :name => "Rishikesh", :region => "Uttaranchal"
    City.create :name => "Dum dum", :region => "West Bengal"
    City.create :name => "Durgapurmc", :region => "West Bengal"
    City.create :name => "Howrah", :region => "West Bengal"
    City.create :name => "Kolkata", :region => "West Bengal"
    City.create :name => "Siliguri m.c.", :region => "West Bengal"
    City.create :name => "Other city", :region => "West Bengal"
  end

  def self.down
    execute "TRUNCATE table #{City.table_name}"
  end
end
